module.exports = {
	'player1': null,
	'player2': null,
	'stageWidth': 2846,
	'stageHeight': 1600,
	'stageCenterX': 1423,
	'stageCenterY': 800,
	'UP': 'up',
	'LEFT': 'left',
	'RIGHT': 'right',
	'DOWN': 'down',
	'UP_LEFT': 'upleft',
	'UP_RIGHT': 'upright',
	'DOWN_LEFT': 'downleft',
	'DOWN_RIGHT': 'downright',
	'CENTER': 'center',
	'gameObjectsJsonUri': '/data/gameobjects.json',
	'levelsJsonUri': '/data/levels.json',
	'fireBtnJsonUri': '/data/fire.json',
	'fireBtnImage': '/img/fire.png',
	'joystickJsonUri': '/data/joystick.json',
	'joystickImage': '/img/joystick.png',
	'spritesJsonUri': '/data/sprites.json'
}