module.exports = {
	'player1': null,
	'player2': null,
	'maxWidth': 2846,
	'maxHeight': 1600,
	'stageCenterX': 1423,
	'stageCenterY': 800,
	'hdWidth': 2846,
	'hdHeight': 1600,
	'mdWidth': 1423,
	'mdHeight': 800,
	'sdWidth': 712,
	'sdHeight': 400,
	'UP': 0,
	'LEFT': 3 * Math.PI / 2,
	'RIGHT': Math.PI / 2,
	'DOWN': Math.PI,
	'UP_LEFT': 7 * Math.PI / 4,
	'UP_RIGHT': Math.PI / 4,
	'DOWN_LEFT': 5 * Math.PI / 4,
	'DOWN_RIGHT': 3 * Math.PI / 4,
	'CENTER': -1,
	'settingsJsonUri': '/data/settings.json',
	'levelsJsonUri': '/data/levels.json',
	'fireBtnJsonUri': '/data/fire.json',
	'fireBtnImage': '/img/fire.png',
	'joystickJsonUri': '/data/joystick.json',
	'joystickImage': '/img/joystick.png',
	'spritesJsonUri': '/data/sprites.json',
	'settings': null
}