module.exports = {
	'player1': null,
	'player2': null,
	'stageWidth': 1334,
	'stageHeight': 750,
	'UP': 'up',
	'LEFT': 'left',
	'RIGHT': 'right',
	'DOWN': 'down',
	'UP_LEFT': 'up_left',
	'UP_RIGHT': 'up_right',
	'DOWN_LEFT': 'down_left',
	'DOWN_RIGHT': 'down_right',
	'CENTER': 'center',
	'gameObjectsJsonUri': '/data/gameobjects.json',
	'levelsJsonUri': '/data/levels.json',
	'fireBtnJsonUri': '/data/fire.json',
	'fireBtnImage': '/img/fire.png',
	'joystickJsonUri': '/data/joystick.json',
	'joystickImage': '/img/joystick.png',
	'spriteJsonUri': '/data/sprites.json',
	'spritesImage': '/img/sprites.png',
	'cos45': Math.cos(Math.PI / 4)
}